### ISSUE TITLE
Swift 2 Release

### ISSUE THREAD

**Issue by cohix** [AndreyLunevich/DLImageLoader-iOS#6]
Are there plans for a swift 2 release?

**Comment by AndreyLunevich** [comment]
Hi, Yes.
I going to do it in few weeks.

**Comment by cohix** [comment]
Do you expect there to be any tricky errors in the migration? Could I easily fork and migrate the code?

**Comment by AndreyLunevich** [comment]
Will look something like this:
DLImageLoader.sharedInstance().displayImage...

I think it simple to migrate.

**Comment by AndreyLunevich** [comment]
Hi, you can use swift 2.0 version of DLImageLoader https://github.com/AndreyLunevich/DLImageLoader-iOS/tree/swift

**Comment by cohix** [comment]
That is beautiful, thank you very much.

**Comment by AndreyLunevich** [comment]
Your welcome :)

**Comment by cohix** [comment]
This is one of the most powerful cocoapods I've ever used :)

**Comment by smhk** [comment]
it is utterly incredible.
