### ISSUE TITLE
Any Chance You Can Invoke Your Code Here?

### ISSUE THREAD

**Issue by johnleindesign** [AndreyLunevich/DLImageLoader-iOS#7]
Wondering if your code can work on something like the following?  If yes, could you explain?

SCTableViewSection *Section3 = [self.tableViewModel sectionAtIndex:0];
        Section3.cellActions.lazyLoad = ^(SCTableViewCell *cell, NSIndexPath *indexPath)
        
        {
            
            DLImageView *imageView = (DLImageView *)[cell viewWithTag:1];
            NSString *imageString = (NSString *)[cell.boundObject valueForKey:@"thumbnail"];
            NSString *fullName = [NSString stringWithFormat:@"Documents/%@", imageString];
            NSString *imagePath = [NSHomeDirectory() stringByAppendingPathComponent:fullName];
            UIImage *originalImage = [UIImage imageWithContentsOfFile:imagePath];
            NSLog(@"added image from lazyload");
            
            // size of actual thumbnail to display in cell
            CGSize destinationSize = CGSizeMake(154,95); // size of actual thumbnail
            UIGraphicsBeginImageContext(destinationSize);
            [originalImage drawInRect:CGRectMake(0,0,destinationSize.width,destinationSize.height)];
            UIImage *thumbnail = UIGraphicsGetImageFromCurrentImageContext();
            
            UIGraphicsEndImageContext();
            
            [UIView transitionWithView:imageView
                              duration:2.25f
                               options:UIViewAnimationOptionTransitionCrossDissolve
                            animations:^{
                                imageView.image = thumbnail;
                            } completion:nil];
            
        };

**Comment by AndreyLunevich** [comment]
Hello.
I have checked this code:

    UIImage *originalImage = [UIImage imageNamed:@"test.jpg"];
    NSLog(@"added image from lazyload");

    // size of actual thumbnail to display in cell
    CGSize destinationSize = CGSizeMake(154,95); // size of actual thumbnail
    UIGraphicsBeginImageContext(destinationSize);
    [originalImage drawInRect:CGRectMake(0,0,destinationSize.width,destinationSize.height)];
    UIImage *thumbnail = UIGraphicsGetImageFromCurrentImageContext();
    
    UIGraphicsEndImageContext();
    
    [UIView transitionWithView:self.thumbnailView
                      duration:2.25f
                       options:UIViewAnimationOptionTransitionCrossDissolve
                    animations:^{
                        self.thumbnailView.image = thumbnail;
                    } completion:nil];

Image is here.

I have few variants why you didn't see the image:
1 - originalImage if nil
2 - if originalImage is not nil try add [imageView setNeedsDisplay];

Let me know if it works.
