### ISSUE TITLE
'init(request:delegate:)' was deprecated in iOS 9.0: Use NSURLSession (see NSURLSession.h)

### ISSUE THREAD

**Issue by qizt** [AndreyLunevich/DLImageLoader-iOS#9]
It seems that NSURLConnection API has been deprecated in iOS 9. 
I'm not sure whether this would affect on the app submission to Apple App Store.
But it would be perfect if we can switch from NSURLConnection to NSURLSession, isn't it?

My Xcode version: 7.3 (7D175).

<img width="1135" alt="screen shot 2016-04-14 at 12 20 11" src="https://cloud.githubusercontent.com/assets/7324708/14537218/af2f0664-023b-11e6-8b4a-51346898eb93.png">

**Comment by AndreyLunevich** [comment]
Hi,
You are right. 
I know about this, but for now don't have a time.
I'm going to update in few days.
